const HEADING_LETTER_SPACING = -0.5
const LABEL_LETTER_SPACING = 0.9
const DISABLED_OPACITY = 0.4
const LINK_PRESS_OPACITY = 0.7
const PAYWALL_SUCCESS_ALERT_DURATION = 4
const SIMULATOR_TOAST_DURATION = 3

export {
  HEADING_LETTER_SPACING,
  LABEL_LETTER_SPACING,
  DISABLED_OPACITY,
  LINK_PRESS_OPACITY,
  PAYWALL_SUCCESS_ALERT_DURATION,
  SIMULATOR_TOAST_DURATION,
}
